### PR TITLE
Community Thread

### PR DESCRIPTION
**Pull request by sol-znn**
Discussion: https://github.com/zenon-network/twitter/pull/14

I did the following:
- Aggregated all tweets mentioned in the discussion, removing duplicates, and confirmed they're still active
- Tested the image and retweet formatting
- Added three hashtags (first and third posts). Feel free to remove them.

### CODE REVIEW

**Comment by sol-znn** [comment]
The workflow is failing because the media image is not available in `master`. 
It should pass (I tested this) when this PR is merged.

[Example result](https://github.com/zenon-network/twitter/assets/104875699/cee4897b-08d2-4a0b-9371-f7b88579af08)

**Review by 0x3639 — APPROVED** [review]

**Comment by 0x3639** [comment]
@Sol-Sanctum I approved it.  Let's see if it pulls the media in.

**Review by coinselor — APPROVED** [review]
LFG! Thank you for taking the time to submit a new PR as well as reference the last one :)))

Let's finally test a workflow with media.

**Comment by 0x3639** [comment]
@Sol-Sanctum 

Media file /home/runner/work/twitter/twitter/media/tribute.png does not exist

**Comment by sol-znn** [comment]
> Media file /home/runner/work/twitter/twitter/media/tribute.png does not exist

I'm aware, but I thought the merge action would correct it.

https://github.com/zenon-network/twitter/pull/21#issuecomment-1756836926

**Comment by 0x3639** [comment]
Not sure what is going on with the media.  I tested this and got the same result.  I'll try in my personal repo and see what happens.

**Comment by sol-znn** [comment]
I expected the merge to succeed. If it doesn't work, we just need a separate PR that adds the image to the media folder.

**Pull request merged**
