### PR TITLE
for next bridging

### PR DESCRIPTION
**Pull request by rainbowginger**

### CODE REVIEW

**Review by rainbowginger — COMMENTED** [review]
To assess community interest and to let others know things are happening

**Review by 0x3639 — APPROVED** [review]

**Comment by sol-znn** [comment]
Should confirm this works before posting on the main account. Format looks correct.

**Comment by rainbowginger** [comment]
> Should confirm this works before posting on the main account. Format looks correct.

How to test it?

**Comment by 0x3639** [comment]
> > Should confirm this works before posting on the main account. Format looks correct.
> 
> How to test it?

We can do manually.  I will test it after work in my account.

**Comment by rainbowginger** [comment]
Does new API change affect polls?

**Comment by 0x3639** [comment]
We need to test on a different repo.  We can do that today.

**Comment by rainbowginger** [comment]
Did it work?

**Comment by 0x3639** [comment]
It worked

Screenshot 2023-10-23 at 6 37 39 PM

**Comment by 0x3639** [comment]
> Did it work?

Maybe add #ZenonNetwork hashtag?

**Comment by sol-znn** [comment]
> It worked
> Screenshot 2023-10-23 at 6 37 39 PM

Is this the expected result? It doesn't look like a poll to me.

**Comment by 0x3639** [comment]
Ummm. No???

image

**Comment by rainbowginger** [comment]
> It worked
> 
> Screenshot 2023-10-23 at 6 37 39 PM
> 
> 

Doesn't seem like it worked . Where you able to select options?

**Comment by rainbowginger** [comment]
> > Did it work?
> 
> Maybe add #ZenonNetwork hashtag?  

Add hashtags of everything in the list.

**Comment by coinselor** [comment]
> Ummm. No???
> 
> image

This looks like a working test. What syntax did you use? Is it the same as the one in the original PR?

**Comment by coinselor** [comment]
```
---
poll:
  - USDT
  - WBTC
  - ETH
  - USDC
  - None of the above
  - Others (please comment below)
---

Which ERC-20 tokens would you like to see on NoM next?
```

I suggest we try this format instead. @rainbowginger can you amend the original PR?

**Pull request closed without merging**
