### PR TITLE
0x3639 Community Tweet

### PR DESCRIPTION
**Pull request by 0x3639**
Attempt community tweet again

### CODE REVIEW

**Comment by sol-znn** [comment]
Why recreate it? I don't think mine was merged. Was there a problem?

**Comment by 0x3639** [comment]
ya, it failed.  It cannot find the media file.  I'm going to close this one so we don't accidentally tweet it twice.

**Comment by sol-znn** [comment]
I guess a separate PR is required for media. Strange, I didn't encounter this issue...

**Comment by 0x3639** [comment]
> I guess a separate PR is required for media. Strange, I didn't encounter this issue...

Meaning the media cannot be with the tweet in the same PR?

**Pull request closed without merging**
