### PR TITLE
add video contest tweet

### PR DESCRIPTION
**Pull request by coinselor**
From: https://github.com/coinselor/twitter/issues/13

Discussion: https://github.com/coinselor/twitter/discussions/12

### CODE REVIEW

**Review by 0x3639 — APPROVED** [review]

**Review by sugoibtc — APPROVED** [review]

**Comment by 0x3639** [comment]
@coinselor looks like we have an invalid character

https://github.com/zenon-network/twitter/actions/runs/7615910694/job/20741479012?pr=45

**Review by sugoibtc — COMMENTED** [review]
line 13 needs to be

retweet: https://twitter.com/Learn_Zenon/status/1748770462887256333

**Comment by 0x3639** [comment]
> line 13 needs to be
> 
> retweet: https://twitter.com/Learn_Zenon/status/1748770462887256333

Actually retweet: does not work with the free API.

**Comment by 0x3639** [comment]
I think these `---` are to blame.

**Comment by 0x3639** [comment]
Can someone submit a new PR without those in the body of the tweet?  Remember the file needs to end with `.tweet`  

So `file-name.tweet`

**Comment by coinselor** [comment]
Weird. I thought I didn't need the last frontmatter '---' delimitation after the reply, as it was unintendedly tweeted out last time. Keep in mind I was going for tweet + reply. Maybe I need to add them in the beginning of the file too.

**Pull request closed without merging**
