### PR TITLE
Reply to Danny Huuep

### PR DESCRIPTION
**Pull request by stark-of-zenon**
- New Twitter algo may give more weight to replies. 
- @huuep is a leading developer in Ordinals
- The original tweet is esoteric and demonstrates an affinity for the philosophical side of the tech
- The original tweet sets the stage
- Exposure to a target audience

### CODE REVIEW

**Comment by sumamu** [comment]
Nice reply! I'd approve.

**Comment by sol-znn** [comment]
Please refer to the [documentation](https://github.com/marketplace/actions/twitter-together) for tweet formatting.

Example reply
```
---
reply: https://twitter.com/huuep/status/1688946337306578944
---

Bitcoin is the mineral grade digital asset. With Bitcoin as terra firma, Zenon and Quasar, the second and third states of digital matter, work together in the Network of Momentum (NoM) to enable the 4th-state feeless plasma paradigm. If Bitcoin is marble, NoM is __________.
```

**Review by 0x3639 — APPROVED** [review]

**Comment by stark-of-zenon** [comment]
> Nice reply! I'd approve.

Are permissions or a certain role required to approve?

**Comment by 0x3639** [comment]
Yes - these people can approve tweets  @mehowz have a look at some of the tweets for review / approval.

image

**Review by 0x3639 — CHANGES_REQUESTED** [review]
Remove this commit from this PR.  You need to create a new PR for this tweet.

**Comment by sumamu** [comment]
> Yes - these people can approve tweets @mehowz have a look at some of the tweets for review / approval.
> 
> image

Should we get more Alienz on that list? I'm seeing some around that are both willing and capable.

**Comment by 0x3639** [comment]
Yes.  I think that is a good idea.  Specifically I think we should add @sumamu and @Sol-Sanctum.  Sumamu tweets a lot and Sol can help with reviewing.

**Comment by sumamu** [comment]
I was thinking about others who have expressed interest in this activity on the forum: Stark, Coinselor, Shazz, Zyler, Brat, Zashu and maybe Romeo, Angelo if they're interested.

We should aim for a mix of tech, marketing and hype.

**Comment by general-stark** [comment]
How about adding:

@coinselor, @sumamu, and Angelo and making it 3/5 quorum?

**Comment by stark-of-zenon** [comment]
@coinselor, @sumamu, @Sol-Sanctum, and Angelo are the names that immediately come to mind

**Comment by sol-znn** [comment]
I can help review formatting and test on my account, if needed. I don't need approval permissions.

I agree with Sumamu's suggestions.

**Comment by 0x3639** [comment]
I'm going to close this PR.  It's too old to post.

**Pull request closed without merging**
