### PR TITLE
Create 1st-community-tweet.tweet

### PR DESCRIPTION
**Pull request by 0x3639**

### CODE REVIEW

**Comment by 0x3639** [comment]
This post was first written by @coinselor here: https://forum.zenon.org/t/official-twitter-posts/1559/31?u=0x3639

**Review by stark-of-zenon — APPROVED** [review]
Engage.

**Comment by 0x3639** [comment]
> Engage.

??  Typo somewhere?

**Comment by stark-of-zenon** [comment]
Quoting Captain Picard, Sir.

> > Engage.
> 
> ?? Typo somewhere?

**Comment by 0x3639** [comment]
all right boyz...  I fixed this tweet.  It's passing tests.  the first tweet was 286 characters so I fixed that.

**Comment by Zen-DAO** [comment]
"#thealinesknow" - is this a typo?

**Comment by Zen-DAO** [comment]
This is a great tweet, but the communication seems directed towards the community. How will it be perceived by the outsiders?

**Comment by 0x3639** [comment]
> "#thealinesknow" - is this a typo?

This is in reference to a typo from @zenon_network.  It's sort of a community meme.  It's probably not good to perpetuate from the official account.

**Comment by 0x3639** [comment]
> This is a great tweet, but the communication seems directed towards the community. How will it be perceived by the outsiders?

True.   Just wanted to offer some options.  I can close this one.

**Pull request closed without merging**
