### PR TITLE
Update README for retweeting

### PR DESCRIPTION
**Pull request by georgezgeorgez**

### CODE REVIEW

**Review by 0x3639 — APPROVED** [review]

**Comment by rainbowginger** [comment]
Example for quote retweet?

-``` retweet random sample quote : https://twitter.com/gr2m/status/1409601188362809349```

**Comment by coinselor** [comment]
I'm assuming retweets do not work, given Sol's/0x research.

❌ Don't do this 
```
---
retweet: https://x.com/Zenon_Network/status/1713226930965872778
---
```

❔ Does quote retweet work?

```
---
retweet: https://x.com/Zenon_Network/status/1713226930965872778
---
Add your tweet text here
```

👍 Our best workaround, a commentary + link to tweet (It won't appear as a native retweet):

```
This amazing tweet by george deserves tweet of the epoch https://x.com/Zenon_Network/status/1713226930965872778
```

Alternatively, we could just do a "budget" retweet by just sharing a twitter link, which is what we tried to do, but please do not add the 'retweet:' word, as it looks terrible.

```
https://x.com/Zenon_Network/status/1713226930965872778
```

**Comment by sol-znn** [comment]
Quote retweets are retweets; they won't work for us.

**Comment by 0x3639** [comment]
> https://x.com/Zenon_Network/status/1713226930965872778

agree.

This will work

https://x.com/Zenon_Network/status/1713226930965872778

and if you do this:

retweet: https://x.com/Zenon_Network/status/1713226930965872778

you will see the test `retweet:` before link in the tweet.  So the only option we have to "retweet" is make an original tweet with text and a link to the tweet we want to reference.

**Comment by 0x3639** [comment]
Maybe need to change to this?  These instructions are not so good.  We probably need to test all of them  
```
---
poll:
  - Red
  - Blue
  - Green
---

What is your favorite color?
```

**Pull request closed without merging**
